name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]

    steps:
      - name: Setup SSH and Deploy Changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/html/payroll
            git pull
            #npx sequelize-cli db:migrate
            npm install uuid
            sudo systemctl stop employee-app
            sudo systemctl start employee-app
